# Generated by Django 4.2.1 on 2023-08-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('stu_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=300)),
                ('lastName', models.CharField(max_length=260)),
                ('password', models.CharField(max_length=300)),
                ('batch', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
