# Generated by Django 4.2.1 on 2023-08-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamesh', '0002_students_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='dept',
            field=models.CharField(max_length=100),
        ),
    ]
