# Generated by Django 4.2.1 on 2023-08-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamesh', '0003_alter_students_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='stu_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
