# Generated by Django 4.2.1 on 2023-08-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamesh', '0004_alter_students_stu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='dept',
            field=models.CharField(max_length=200),
        ),
    ]
