# Generated by Django 4.2.1 on 2023-08-05 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metamesh', '0005_alter_students_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('text', models.CharField(max_length=10000)),
                ('upvote', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100)),
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.students')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
