# Generated by Django 4.2.1 on 2023-08-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamesh', '0006_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='upvote',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
