# Generated by Django 4.2.1 on 2023-08-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metamesh', '0007_alter_posts_upvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='_id',
            new_name='iid',
        ),
    ]
