# Generated by Django 4.2.1 on 2023-08-07 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metamesh', '0009_alter_posts_upvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.CharField(default='0', max_length=100, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.students')),
            ],
            options={
                'db_table': 'like',
            },
        ),
    ]
