# Generated by Django 4.2.1 on 2023-08-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamesh', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='active',
            field=models.CharField(default='false', max_length=20),
        ),
    ]
