# Generated by Django 4.2.1 on 2023-08-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metamesh', '0013_club'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='club',
            new_name='clubs',
        ),
    ]
