# Generated by Django 4.2.1 on 2023-08-07 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metamesh', '0014_rename_club_clubs'),
    ]

    operations = [
        migrations.CreateModel(
            name='clubApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='not', max_length=100)),
                ('clubid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.clubs')),
                ('studentss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.students')),
            ],
            options={
                'db_table': 'approval',
            },
        ),
    ]
