# Generated by Django 4.2.1 on 2023-08-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamesh', '0015_clubapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubapproval',
            name='admin',
            field=models.CharField(default='', max_length=100),
        ),
    ]
