# Generated by Django 4.2.1 on 2023-08-07 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metamesh', '0016_clubapproval_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='clubpost',
            fields=[
                ('texts', models.CharField(default='', max_length=300)),
                ('iid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('upvote', models.CharField(max_length=200, null=True)),
                ('clubidd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.clubs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.students')),
            ],
            options={
                'db_table': 'clubpost',
            },
        ),
    ]
