# Generated by Django 4.2.1 on 2023-08-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metamesh', '0017_clubpost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clubapproval',
            unique_together={('clubid', 'studentss')},
        ),
    ]
