# Generated by Django 4.2.1 on 2023-08-09 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metamesh', '0018_alter_clubapproval_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubpost',
            name='upvote',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='clublikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.CharField(default='0', max_length=100, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.clubs')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.clubpost')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.students')),
            ],
            options={
                'db_table': 'clublikes',
            },
        ),
    ]
