# Generated by Django 4.2.1 on 2023-08-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamesh', '0019_alter_clubpost_upvote_clublikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpost',
            name='cimage',
            field=models.ImageField(null=True, upload_to='cposts'),
        ),
        migrations.AddField(
            model_name='clubs',
            name='imagee',
            field=models.ImageField(null=True, upload_to='fimage'),
        ),
        migrations.AddField(
            model_name='posts',
            name='pictures',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='students',
            name='profpic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
