# Generated by Django 4.2.1 on 2023-08-11 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metamesh', '0023_alter_event_banner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event',
            new_name='eevent',
        ),
        migrations.RenameField(
            model_name='eevent',
            old_name='banner',
            new_name='bannerImg',
        ),
    ]
