# Generated by Django 4.2.1 on 2023-08-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamesh', '0024_rename_event_eevent_rename_banner_eevent_bannerimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
