# Generated by Django 4.2.1 on 2023-08-18 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metamesh', '0025_likes_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='conversations',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pkk', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('userss', models.ManyToManyField(to='metamesh.students')),
            ],
            options={
                'db_table': 'conversations',
            },
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('post', 'user')},
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(default='', max_length=300, null=True)),
                ('convs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.conversations')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.students')),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
