# Generated by Django 4.2.1 on 2023-08-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamesh', '0026_conversations_alter_likes_unique_together_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eevent',
            name='id',
        ),
        migrations.AlterField(
            model_name='eevent',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
